---
# This workflow integrates ShiftLeft with GitHub
# Visit https://docs.shiftleft.io for help
name: Qwiet AI

on:
  push:
    branches:
     - master
     - main
  pull_request:
  workflow_dispatch:

jobs:
  preZero:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: AppThreat/cpggen-action@main
      with:
        lang: jar
      env:
        SL_CPG_OPTS: "-J-Xms2g -J-Xmx7g"
        SHIFTLEFT_JAVA_OPTS: "-Xms2g -Xmx7g"
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
